name: 🚀 Deploy to EC2

on:
  push:
    branches:
      - main   # or 'main' if you renamed it

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/minishop
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d --build
